export interface DigiflazzProduct {
  buyer_sku_code: string;
  product_name: string;
  category: string;
  brand: string;
  type: string;
  seller_name: string;
  price: number;
  buyer_product_status: boolean;
  seller_product_status: boolean;
  unlimited_stock: boolean;
  stock: number;
  multi: boolean;
  start_cut_off: string;
  end_cut_off: string;
  desc: string;
}

export const DEFAULT_PREPAID_PRODUCTS: DigiflazzProduct[] = [
  // --- GAMES: FREE FIRE ---
  {
    buyer_sku_code: "FF5",
    product_name: "Free Fire 5 Diamond",
    category: "Games",
    brand: "FREE FIRE",
    type: "Umum",
    seller_name: "Garena Official",
    price: 850,
    buyer_product_status: true,
    seller_product_status: true,
    unlimited_stock: true,
    stock: 9999,
    multi: true,
    start_cut_off: "23:55",
    end_cut_off: "00:05",
    desc: "Top up Free Fire 5 Diamond Instant 24 Jam"
  },
  {
    buyer_sku_code: "FF12",
    product_name: "Free Fire 12 Diamond",
    category: "Games",
    brand: "FREE FIRE",
    type: "Umum",
    seller_name: "Garena Official",
    price: 1900,
    buyer_product_status: true,
    seller_product_status: true,
    unlimited_stock: true,
    stock: 9999,
    multi: true,
    start_cut_off: "23:55",
    end_cut_off: "00:05",
    desc: "Top up Free Fire 12 Diamond Instant 24 Jam"
  },
  {
    buyer_sku_code: "FF50",
    product_name: "Free Fire 50 Diamond",
    category: "Games",
    brand: "FREE FIRE",
    type: "Umum",
    seller_name: "Garena Official",
    price: 6950,
    buyer_product_status: true,
    seller_product_status: true,
    unlimited_stock: true,
    stock: 9999,
    multi: true,
    start_cut_off: "23:55",
    end_cut_off: "00:05",
    desc: "Top up Free Fire 50 Diamond Instant"
  },
  {
    buyer_sku_code: "FF70",
    product_name: "Free Fire 70 Diamond",
    category: "Games",
    brand: "FREE FIRE",
    type: "Umum",
    seller_name: "Garena Official",
    price: 9350,
    buyer_product_status: true,
    seller_product_status: true,
    unlimited_stock: true,
    stock: 9999,
    multi: true,
    start_cut_off: "23:55",
    end_cut_off: "00:05",
    desc: "Top up Free Fire 70 Diamond Instant"
  },
  {
    buyer_sku_code: "FF140",
    product_name: "Free Fire 140 Diamond",
    category: "Games",
    brand: "FREE FIRE",
    type: "Umum",
    seller_name: "Garena Official",
    price: 18500,
    buyer_product_status: true,
    seller_product_status: true,
    unlimited_stock: true,
    stock: 9999,
    multi: true,
    start_cut_off: "23:55",
    end_cut_off: "00:05",
    desc: "Top up Free Fire 140 Diamond Instant"
  },
  {
    buyer_sku_code: "FF210",
    product_name: "Free Fire 210 Diamond",
    category: "Games",
    brand: "FREE FIRE",
    type: "Umum",
    seller_name: "Garena Official",
    price: 27500,
    buyer_product_status: true,
    seller_product_status: true,
    unlimited_stock: true,
    stock: 9999,
    multi: true,
    start_cut_off: "23:55",
    end_cut_off: "00:05",
    desc: "Top up Free Fire 210 Diamond Instant"
  },
  {
    buyer_sku_code: "FF355",
    product_name: "Free Fire 355 Diamond",
    category: "Games",
    brand: "FREE FIRE",
    type: "Umum",
    seller_name: "Garena Official",
    price: 46000,
    buyer_product_status: true,
    seller_product_status: true,
    unlimited_stock: true,
    stock: 9999,
    multi: true,
    start_cut_off: "23:55",
    end_cut_off: "00:05",
    desc: "Top up Free Fire 355 Diamond Instant"
  },
  {
    buyer_sku_code: "FF720",
    product_name: "Free Fire 720 Diamond",
    category: "Games",
    brand: "FREE FIRE",
    type: "Umum",
    seller_name: "Garena Official",
    price: 91500,
    buyer_product_status: true,
    seller_product_status: true,
    unlimited_stock: true,
    stock: 9999,
    multi: true,
    start_cut_off: "23:55",
    end_cut_off: "00:05",
    desc: "Top up Free Fire 720 Diamond Instant"
  },
  {
    buyer_sku_code: "FF1440",
    product_name: "Free Fire 1440 Diamond",
    category: "Games",
    brand: "FREE FIRE",
    type: "Umum",
    seller_name: "Garena Official",
    price: 183000,
    buyer_product_status: true,
    seller_product_status: true,
    unlimited_stock: true,
    stock: 9999,
    multi: true,
    start_cut_off: "23:55",
    end_cut_off: "00:05",
    desc: "Top up Free Fire 1440 Diamond Instant"
  },
  {
    buyer_sku_code: "FFMEMW",
    product_name: "Free Fire Membership Mingguan",
    category: "Games",
    brand: "FREE FIRE",
    type: "Umum",
    seller_name: "Garena Official",
    price: 28000,
    buyer_product_status: true,
    seller_product_status: true,
    unlimited_stock: true,
    stock: 9999,
    multi: true,
    start_cut_off: "23:55",
    end_cut_off: "00:05",
    desc: "Free Fire Weekly Diamond Membership"
  },
  {
    buyer_sku_code: "FFMEMM",
    product_name: "Free Fire Membership Bulanan",
    category: "Games",
    brand: "FREE FIRE",
    type: "Umum",
    seller_name: "Garena Official",
    price: 80000,
    buyer_product_status: true,
    seller_product_status: true,
    unlimited_stock: true,
    stock: 9999,
    multi: true,
    start_cut_off: "23:55",
    end_cut_off: "00:05",
    desc: "Free Fire Monthly Diamond Membership"
  },
  {
    buyer_sku_code: "FFLUP",
    product_name: "Free Fire Level Up Pass",
    category: "Games",
    brand: "FREE FIRE",
    type: "Umum",
    seller_name: "Garena Official",
    price: 15000,
    buyer_product_status: true,
    seller_product_status: true,
    unlimited_stock: true,
    stock: 9999,
    multi: true,
    start_cut_off: "23:55",
    end_cut_off: "00:05",
    desc: "Free Fire Level Up Pass Instant"
  },

  // --- GAMES: MOBILE LEGENDS (Accurate prices sorted by diamonds) ---
  {
    buyer_sku_code: "ML3",
    product_name: "Mobile Legends 3 Diamonds",
    category: "Games",
    brand: "MOBILE LEGENDS",
    type: "Umum",
    seller_name: "Moonton Official",
    price: 1100,
    buyer_product_status: true,
    seller_product_status: true,
    unlimited_stock: true,
    stock: 9999,
    multi: true,
    start_cut_off: "23:55",
    end_cut_off: "00:05",
    desc: "Top up Mobile Legends 3 Diamonds Fast"
  },
  {
    buyer_sku_code: "ML5",
    product_name: "Mobile Legends 5 Diamonds",
    category: "Games",
    brand: "MOBILE LEGENDS",
    type: "Umum",
    seller_name: "Moonton Official",
    price: 1500,
    buyer_product_status: true,
    seller_product_status: true,
    unlimited_stock: true,
    stock: 9999,
    multi: true,
    start_cut_off: "23:55",
    end_cut_off: "00:05",
    desc: "Top up Mobile Legends 5 Diamonds Fast"
  },
  {
    buyer_sku_code: "ML12",
    product_name: "Mobile Legends 12 Diamonds",
    category: "Games",
    brand: "MOBILE LEGENDS",
    type: "Umum",
    seller_name: "Moonton Official",
    price: 3300,
    buyer_product_status: true,
    seller_product_status: true,
    unlimited_stock: true,
    stock: 9999,
    multi: true,
    start_cut_off: "23:55",
    end_cut_off: "00:05",
    desc: "Top up Mobile Legends 12 Diamonds Fast"
  },
  {
    buyer_sku_code: "ML19",
    product_name: "Mobile Legends 19 Diamonds",
    category: "Games",
    brand: "MOBILE LEGENDS",
    type: "Umum",
    seller_name: "Moonton Official",
    price: 5200,
    buyer_product_status: true,
    seller_product_status: true,
    unlimited_stock: true,
    stock: 9999,
    multi: true,
    start_cut_off: "23:55",
    end_cut_off: "00:05",
    desc: "Top up Mobile Legends 19 Diamonds Fast"
  },
  {
    buyer_sku_code: "ML28",
    product_name: "Mobile Legends 28 Diamonds",
    category: "Games",
    brand: "MOBILE LEGENDS",
    type: "Umum",
    seller_name: "Moonton Official",
    price: 7600,
    buyer_product_status: true,
    seller_product_status: true,
    unlimited_stock: true,
    stock: 9999,
    multi: true,
    start_cut_off: "23:55",
    end_cut_off: "00:05",
    desc: "Top up Mobile Legends 28 Diamonds Fast"
  },
  {
    buyer_sku_code: "ML44",
    product_name: "Mobile Legends 44 Diamonds",
    category: "Games",
    brand: "MOBILE LEGENDS",
    type: "Umum",
    seller_name: "Moonton Official",
    price: 11500,
    buyer_product_status: true,
    seller_product_status: true,
    unlimited_stock: true,
    stock: 9999,
    multi: true,
    start_cut_off: "23:55",
    end_cut_off: "00:05",
    desc: "Top up Mobile Legends 44 Diamonds Fast"
  },
  {
    buyer_sku_code: "ML59",
    product_name: "Mobile Legends 59 Diamonds",
    category: "Games",
    brand: "MOBILE LEGENDS",
    type: "Umum",
    seller_name: "Moonton Official",
    price: 15200,
    buyer_product_status: true,
    seller_product_status: true,
    unlimited_stock: true,
    stock: 9999,
    multi: true,
    start_cut_off: "23:55",
    end_cut_off: "00:05",
    desc: "Top up Mobile Legends 59 Diamonds Fast"
  },
  {
    buyer_sku_code: "ML85",
    product_name: "Mobile Legends 85 Diamonds",
    category: "Games",
    brand: "MOBILE LEGENDS",
    type: "Umum",
    seller_name: "Moonton Official",
    price: 21500,
    buyer_product_status: true,
    seller_product_status: true,
    unlimited_stock: true,
    stock: 9999,
    multi: true,
    start_cut_off: "23:55",
    end_cut_off: "00:05",
    desc: "Top up Mobile Legends 85 Diamonds Fast"
  },
  {
    buyer_sku_code: "ML170",
    product_name: "Mobile Legends 170 Diamonds",
    category: "Games",
    brand: "MOBILE LEGENDS",
    type: "Umum",
    seller_name: "Moonton Official",
    price: 43000,
    buyer_product_status: true,
    seller_product_status: true,
    unlimited_stock: true,
    stock: 9999,
    multi: true,
    start_cut_off: "23:55",
    end_cut_off: "00:05",
    desc: "Top up Mobile Legends 170 Diamonds Fast"
  },
  {
    buyer_sku_code: "ML240",
    product_name: "Mobile Legends 240 Diamonds",
    category: "Games",
    brand: "MOBILE LEGENDS",
    type: "Umum",
    seller_name: "Moonton Official",
    price: 60500,
    buyer_product_status: true,
    seller_product_status: true,
    unlimited_stock: true,
    stock: 9999,
    multi: true,
    start_cut_off: "23:55",
    end_cut_off: "00:05",
    desc: "Top up Mobile Legends 240 Diamonds Fast"
  },
  {
    buyer_sku_code: "ML296",
    product_name: "Mobile Legends 296 Diamonds",
    category: "Games",
    brand: "MOBILE LEGENDS",
    type: "Umum",
    seller_name: "Moonton Official",
    price: 74500,
    buyer_product_status: true,
    seller_product_status: true,
    unlimited_stock: true,
    stock: 9999,
    multi: true,
    start_cut_off: "23:55",
    end_cut_off: "00:05",
    desc: "Top up Mobile Legends 296 Diamonds Fast"
  },
  {
    buyer_sku_code: "ML408",
    product_name: "Mobile Legends 408 Diamonds",
    category: "Games",
    brand: "MOBILE LEGENDS",
    type: "Umum",
    seller_name: "Moonton Official",
    price: 102500,
    buyer_product_status: true,
    seller_product_status: true,
    unlimited_stock: true,
    stock: 9999,
    multi: true,
    start_cut_off: "23:55",
    end_cut_off: "00:05",
    desc: "Top up Mobile Legends 408 Diamonds Fast"
  },
  {
    buyer_sku_code: "ML568",
    product_name: "Mobile Legends 568 Diamonds",
    category: "Games",
    brand: "MOBILE LEGENDS",
    type: "Umum",
    seller_name: "Moonton Official",
    price: 142000,
    buyer_product_status: true,
    seller_product_status: true,
    unlimited_stock: true,
    stock: 9999,
    multi: true,
    start_cut_off: "23:55",
    end_cut_off: "00:05",
    desc: "Top up Mobile Legends 568 Diamonds Fast"
  },
  {
    buyer_sku_code: "ML875",
    product_name: "Mobile Legends 875 Diamonds",
    category: "Games",
    brand: "MOBILE LEGENDS",
    type: "Umum",
    seller_name: "Moonton Official",
    price: 215000,
    buyer_product_status: true,
    seller_product_status: true,
    unlimited_stock: true,
    stock: 9999,
    multi: true,
    start_cut_off: "23:55",
    end_cut_off: "00:05",
    desc: "Top up Mobile Legends 875 Diamonds Fast"
  },
  {
    buyer_sku_code: "MLWDP",
    product_name: "Mobile Legends Weekly Diamond Pass",
    category: "Games",
    brand: "MOBILE LEGENDS",
    type: "Umum",
    seller_name: "Moonton Official",
    price: 26500,
    buyer_product_status: true,
    seller_product_status: true,
    unlimited_stock: true,
    stock: 9999,
    multi: true,
    start_cut_off: "23:55",
    end_cut_off: "00:05",
    desc: "Mobile Legends Weekly Diamond Pass"
  },
  {
    buyer_sku_code: "MLTP",
    product_name: "Mobile Legends Twilight Pass",
    category: "Games",
    brand: "MOBILE LEGENDS",
    type: "Umum",
    seller_name: "Moonton Official",
    price: 135000,
    buyer_product_status: true,
    seller_product_status: true,
    unlimited_stock: true,
    stock: 9999,
    multi: true,
    start_cut_off: "23:55",
    end_cut_off: "00:05",
    desc: "Mobile Legends Twilight Pass Instant"
  },

  // --- GAMES: PUBG MOBILE ---
  {
    buyer_sku_code: "PUBG35",
    product_name: "PUBG Mobile 35 Unknown Cash (UC)",
    category: "Games",
    brand: "PUBG MOBILE",
    type: "Umum",
    seller_name: "Tencent Official",
    price: 7500,
    buyer_product_status: true,
    seller_product_status: true,
    unlimited_stock: true,
    stock: 9999,
    multi: true,
    start_cut_off: "23:55",
    end_cut_off: "00:05",
    desc: "Top up PUBG Mobile 35 UC"
  },
  {
    buyer_sku_code: "PUBG52",
    product_name: "PUBG Mobile 52 Unknown Cash (UC)",
    category: "Games",
    brand: "PUBG MOBILE",
    type: "Umum",
    seller_name: "Tencent Official",
    price: 11000,
    buyer_product_status: true,
    seller_product_status: true,
    unlimited_stock: true,
    stock: 9999,
    multi: true,
    start_cut_off: "23:55",
    end_cut_off: "00:05",
    desc: "Top up PUBG Mobile 52 UC"
  },
  {
    buyer_sku_code: "PUBG70",
    product_name: "PUBG Mobile 70 Unknown Cash (UC)",
    category: "Games",
    brand: "PUBG MOBILE",
    type: "Umum",
    seller_name: "Tencent Official",
    price: 14500,
    buyer_product_status: true,
    seller_product_status: true,
    unlimited_stock: true,
    stock: 9999,
    multi: true,
    start_cut_off: "23:55",
    end_cut_off: "00:05",
    desc: "Top up PUBG Mobile 70 UC"
  },
  {
    buyer_sku_code: "PUBG100",
    product_name: "PUBG Mobile 100 Unknown Cash (UC)",
    category: "Games",
    brand: "PUBG MOBILE",
    type: "Umum",
    seller_name: "Tencent Official",
    price: 21000,
    buyer_product_status: true,
    seller_product_status: true,
    unlimited_stock: true,
    stock: 9999,
    multi: true,
    start_cut_off: "23:55",
    end_cut_off: "00:05",
    desc: "Top up PUBG Mobile 100 UC"
  },
  {
    buyer_sku_code: "PUBG210",
    product_name: "PUBG Mobile 210 Unknown Cash (UC)",
    category: "Games",
    brand: "PUBG MOBILE",
    type: "Umum",
    seller_name: "Tencent Official",
    price: 43500,
    buyer_product_status: true,
    seller_product_status: true,
    unlimited_stock: true,
    stock: 9999,
    multi: true,
    start_cut_off: "23:55",
    end_cut_off: "00:05",
    desc: "Top up PUBG Mobile 210 UC"
  },

  // --- GAMES: GENSHIN IMPACT ---
  {
    buyer_sku_code: "GENSHIN60",
    product_name: "Genshin Impact 60 Genesis Crystals",
    category: "Games",
    brand: "GENSHIN IMPACT",
    type: "Umum",
    seller_name: "HoYoverse",
    price: 14000,
    buyer_product_status: true,
    seller_product_status: true,
    unlimited_stock: true,
    stock: 9999,
    multi: true,
    start_cut_off: "23:55",
    end_cut_off: "00:05",
    desc: "Genshin Impact 60 Crystals Instant"
  },
  {
    buyer_sku_code: "GENSHIN300",
    product_name: "Genshin Impact 300+30 Genesis Crystals",
    category: "Games",
    brand: "GENSHIN IMPACT",
    type: "Umum",
    seller_name: "HoYoverse",
    price: 70000,
    buyer_product_status: true,
    seller_product_status: true,
    unlimited_stock: true,
    stock: 9999,
    multi: true,
    start_cut_off: "23:55",
    end_cut_off: "00:05",
    desc: "Genshin Impact 330 Crystals Instant"
  },
  {
    buyer_sku_code: "GENSHINWELKIN",
    product_name: "Genshin Impact Blessing of the Welkin Moon",
    category: "Games",
    brand: "GENSHIN IMPACT",
    type: "Umum",
    seller_name: "HoYoverse",
    price: 72000,
    buyer_product_status: true,
    seller_product_status: true,
    unlimited_stock: true,
    stock: 9999,
    multi: true,
    start_cut_off: "23:55",
    end_cut_off: "00:05",
    desc: "Welkin Moon 30 Days Instant"
  },

  // --- E-MONEY: DANA ---
  {
    buyer_sku_code: "DANA10",
    product_name: "DANA 10.000",
    category: "E-Money",
    brand: "DANA",
    type: "Umum",
    seller_name: "DANA Indonesia",
    price: 10150,
    buyer_product_status: true,
    seller_product_status: true,
    unlimited_stock: true,
    stock: 9999,
    multi: true,
    start_cut_off: "23:55",
    end_cut_off: "00:05",
    desc: "Top up Saldo DANA 10.000"
  },
  {
    buyer_sku_code: "DANA20",
    product_name: "DANA 20.000",
    category: "E-Money",
    brand: "DANA",
    type: "Umum",
    seller_name: "DANA Indonesia",
    price: 20150,
    buyer_product_status: true,
    seller_product_status: true,
    unlimited_stock: true,
    stock: 9999,
    multi: true,
    start_cut_off: "23:55",
    end_cut_off: "00:05",
    desc: "Top up Saldo DANA 20.000"
  },
  {
    buyer_sku_code: "DANA25",
    product_name: "DANA 25.000",
    category: "E-Money",
    brand: "DANA",
    type: "Umum",
    seller_name: "DANA Indonesia",
    price: 25150,
    buyer_product_status: true,
    seller_product_status: true,
    unlimited_stock: true,
    stock: 9999,
    multi: true,
    start_cut_off: "23:55",
    end_cut_off: "00:05",
    desc: "Top up Saldo DANA 25.000"
  },
  {
    buyer_sku_code: "DANA50",
    product_name: "DANA 50.000",
    category: "E-Money",
    brand: "DANA",
    type: "Umum",
    seller_name: "DANA Indonesia",
    price: 50150,
    buyer_product_status: true,
    seller_product_status: true,
    unlimited_stock: true,
    stock: 9999,
    multi: true,
    start_cut_off: "23:55",
    end_cut_off: "00:05",
    desc: "Top up Saldo DANA 50.000"
  },
  {
    buyer_sku_code: "DANA100",
    product_name: "DANA 100.000",
    category: "E-Money",
    brand: "DANA",
    type: "Umum",
    seller_name: "DANA Indonesia",
    price: 100200,
    buyer_product_status: true,
    seller_product_status: true,
    unlimited_stock: true,
    stock: 9999,
    multi: true,
    start_cut_off: "23:55",
    end_cut_off: "00:05",
    desc: "Top up Saldo DANA 100.000"
  },

  // --- E-MONEY: GOPAY ---
  {
    buyer_sku_code: "GOPAY10",
    product_name: "GoPay 10.000",
    category: "E-Money",
    brand: "GOPAY",
    type: "Umum",
    seller_name: "Gojek Indonesia",
    price: 10150,
    buyer_product_status: true,
    seller_product_status: true,
    unlimited_stock: true,
    stock: 9999,
    multi: true,
    start_cut_off: "23:55",
    end_cut_off: "00:05",
    desc: "Top up GoPay Customer 10.000"
  },
  {
    buyer_sku_code: "GOPAY20",
    product_name: "GoPay 20.000",
    category: "E-Money",
    brand: "GOPAY",
    type: "Umum",
    seller_name: "Gojek Indonesia",
    price: 20150,
    buyer_product_status: true,
    seller_product_status: true,
    unlimited_stock: true,
    stock: 9999,
    multi: true,
    start_cut_off: "23:55",
    end_cut_off: "00:05",
    desc: "Top up GoPay Customer 20.000"
  },
  {
    buyer_sku_code: "GOPAY50",
    product_name: "GoPay 50.000",
    category: "E-Money",
    brand: "GOPAY",
    type: "Umum",
    seller_name: "Gojek Indonesia",
    price: 50150,
    buyer_product_status: true,
    seller_product_status: true,
    unlimited_stock: true,
    stock: 9999,
    multi: true,
    start_cut_off: "23:55",
    end_cut_off: "00:05",
    desc: "Top up GoPay Customer 50.000"
  },
  {
    buyer_sku_code: "GOPAY100",
    product_name: "GoPay 100.000",
    category: "E-Money",
    brand: "GOPAY",
    type: "Umum",
    seller_name: "Gojek Indonesia",
    price: 100200,
    buyer_product_status: true,
    seller_product_status: true,
    unlimited_stock: true,
    stock: 9999,
    multi: true,
    start_cut_off: "23:55",
    end_cut_off: "00:05",
    desc: "Top up GoPay Customer 100.000"
  },

  // --- E-MONEY: OVO ---
  {
    buyer_sku_code: "OVO10",
    product_name: "OVO 10.000",
    category: "E-Money",
    brand: "OVO",
    type: "Umum",
    seller_name: "OVO Indonesia",
    price: 10150,
    buyer_product_status: true,
    seller_product_status: true,
    unlimited_stock: true,
    stock: 9999,
    multi: true,
    start_cut_off: "23:55",
    end_cut_off: "00:05",
    desc: "Top up OVO Cash 10.000"
  },
  {
    buyer_sku_code: "OVO20",
    product_name: "OVO 20.000",
    category: "E-Money",
    brand: "OVO",
    type: "Umum",
    seller_name: "OVO Indonesia",
    price: 20150,
    buyer_product_status: true,
    seller_product_status: true,
    unlimited_stock: true,
    stock: 9999,
    multi: true,
    start_cut_off: "23:55",
    end_cut_off: "00:05",
    desc: "Top up OVO Cash 20.000"
  },
  {
    buyer_sku_code: "OVO50",
    product_name: "OVO 50.000",
    category: "E-Money",
    brand: "OVO",
    type: "Umum",
    seller_name: "OVO Indonesia",
    price: 50150,
    buyer_product_status: true,
    seller_product_status: true,
    unlimited_stock: true,
    stock: 9999,
    multi: true,
    start_cut_off: "23:55",
    end_cut_off: "00:05",
    desc: "Top up OVO Cash 50.000"
  },
  {
    buyer_sku_code: "OVO100",
    product_name: "OVO 100.000",
    category: "E-Money",
    brand: "OVO",
    type: "Umum",
    seller_name: "OVO Indonesia",
    price: 100200,
    buyer_product_status: true,
    seller_product_status: true,
    unlimited_stock: true,
    stock: 9999,
    multi: true,
    start_cut_off: "23:55",
    end_cut_off: "00:05",
    desc: "Top up OVO Cash 100.000"
  },

  // --- E-MONEY: SHOPEEPAY ---
  {
    buyer_sku_code: "SPAY10",
    product_name: "ShopeePay 10.000",
    category: "E-Money",
    brand: "SHOPEEPAY",
    type: "Umum",
    seller_name: "Shopee Indonesia",
    price: 10150,
    buyer_product_status: true,
    seller_product_status: true,
    unlimited_stock: true,
    stock: 9999,
    multi: true,
    start_cut_off: "23:55",
    end_cut_off: "00:05",
    desc: "Top up ShopeePay 10.000"
  },
  {
    buyer_sku_code: "SPAY20",
    product_name: "ShopeePay 20.000",
    category: "E-Money",
    brand: "SHOPEEPAY",
    type: "Umum",
    seller_name: "Shopee Indonesia",
    price: 20150,
    buyer_product_status: true,
    seller_product_status: true,
    unlimited_stock: true,
    stock: 9999,
    multi: true,
    start_cut_off: "23:55",
    end_cut_off: "00:05",
    desc: "Top up ShopeePay 20.000"
  },
  {
    buyer_sku_code: "SPAY50",
    product_name: "ShopeePay 50.000",
    category: "E-Money",
    brand: "SHOPEEPAY",
    type: "Umum",
    seller_name: "Shopee Indonesia",
    price: 50150,
    buyer_product_status: true,
    seller_product_status: true,
    unlimited_stock: true,
    stock: 9999,
    multi: true,
    start_cut_off: "23:55",
    end_cut_off: "00:05",
    desc: "Top up ShopeePay 50.000"
  },
  {
    buyer_sku_code: "SPAY100",
    product_name: "ShopeePay 100.000",
    category: "E-Money",
    brand: "SHOPEEPAY",
    type: "Umum",
    seller_name: "Shopee Indonesia",
    price: 100200,
    buyer_product_status: true,
    seller_product_status: true,
    unlimited_stock: true,
    stock: 9999,
    multi: true,
    start_cut_off: "23:55",
    end_cut_off: "00:05",
    desc: "Top up ShopeePay 100.000"
  },

  // --- PULSA: TELKOMSEL ---
  {
    buyer_sku_code: "TSEL5",
    product_name: "Telkomsel 5.000",
    category: "Pulsa",
    brand: "TELKOMSEL",
    type: "Umum",
    seller_name: "Telkomsel",
    price: 5200,
    buyer_product_status: true,
    seller_product_status: true,
    unlimited_stock: true,
    stock: 9999,
    multi: true,
    start_cut_off: "23:55",
    end_cut_off: "00:05",
    desc: "Pulsa Reguler Telkomsel 5.000"
  },
  {
    buyer_sku_code: "TSEL10",
    product_name: "Telkomsel 10.000",
    category: "Pulsa",
    brand: "TELKOMSEL",
    type: "Umum",
    seller_name: "Telkomsel",
    price: 10250,
    buyer_product_status: true,
    seller_product_status: true,
    unlimited_stock: true,
    stock: 9999,
    multi: true,
    start_cut_off: "23:55",
    end_cut_off: "00:05",
    desc: "Pulsa Reguler Telkomsel 10.000"
  },
  {
    buyer_sku_code: "TSEL20",
    product_name: "Telkomsel 20.000",
    category: "Pulsa",
    brand: "TELKOMSEL",
    type: "Umum",
    seller_name: "Telkomsel",
    price: 20200,
    buyer_product_status: true,
    seller_product_status: true,
    unlimited_stock: true,
    stock: 9999,
    multi: true,
    start_cut_off: "23:55",
    end_cut_off: "00:05",
    desc: "Pulsa Reguler Telkomsel 20.000"
  },
  {
    buyer_sku_code: "TSEL25",
    product_name: "Telkomsel 25.000",
    category: "Pulsa",
    brand: "TELKOMSEL",
    type: "Umum",
    seller_name: "Telkomsel",
    price: 25100,
    buyer_product_status: true,
    seller_product_status: true,
    unlimited_stock: true,
    stock: 9999,
    multi: true,
    start_cut_off: "23:55",
    end_cut_off: "00:05",
    desc: "Pulsa Reguler Telkomsel 25.000"
  },
  {
    buyer_sku_code: "TSEL50",
    product_name: "Telkomsel 50.000",
    category: "Pulsa",
    brand: "TELKOMSEL",
    type: "Umum",
    seller_name: "Telkomsel",
    price: 50100,
    buyer_product_status: true,
    seller_product_status: true,
    unlimited_stock: true,
    stock: 9999,
    multi: true,
    start_cut_off: "23:55",
    end_cut_off: "00:05",
    desc: "Pulsa Reguler Telkomsel 50.000"
  },
  {
    buyer_sku_code: "TSEL100",
    product_name: "Telkomsel 100.000",
    category: "Pulsa",
    brand: "TELKOMSEL",
    type: "Umum",
    seller_name: "Telkomsel",
    price: 99200,
    buyer_product_status: true,
    seller_product_status: true,
    unlimited_stock: true,
    stock: 9999,
    multi: true,
    start_cut_off: "23:55",
    end_cut_off: "00:05",
    desc: "Pulsa Reguler Telkomsel 100.000"
  },

  // --- PULSA: INDOSAT ---
  {
    buyer_sku_code: "ISAT5",
    product_name: "Indosat 5.000",
    category: "Pulsa",
    brand: "INDOSAT",
    type: "Umum",
    seller_name: "Indosat Ooredoo",
    price: 5350,
    buyer_product_status: true,
    seller_product_status: true,
    unlimited_stock: true,
    stock: 9999,
    multi: true,
    start_cut_off: "23:55",
    end_cut_off: "00:05",
    desc: "Pulsa Reguler Indosat 5.000"
  },
  {
    buyer_sku_code: "ISAT10",
    product_name: "Indosat 10.000",
    category: "Pulsa",
    brand: "INDOSAT",
    type: "Umum",
    seller_name: "Indosat Ooredoo",
    price: 10350,
    buyer_product_status: true,
    seller_product_status: true,
    unlimited_stock: true,
    stock: 9999,
    multi: true,
    start_cut_off: "23:55",
    end_cut_off: "00:05",
    desc: "Pulsa Reguler Indosat 10.000"
  },
  {
    buyer_sku_code: "ISAT25",
    product_name: "Indosat 25.000",
    category: "Pulsa",
    brand: "INDOSAT",
    type: "Umum",
    seller_name: "Indosat Ooredoo",
    price: 25150,
    buyer_product_status: true,
    seller_product_status: true,
    unlimited_stock: true,
    stock: 9999,
    multi: true,
    start_cut_off: "23:55",
    end_cut_off: "00:05",
    desc: "Pulsa Reguler Indosat 25.000"
  },
  {
    buyer_sku_code: "ISAT50",
    product_name: "Indosat 50.000",
    category: "Pulsa",
    brand: "INDOSAT",
    type: "Umum",
    seller_name: "Indosat Ooredoo",
    price: 49800,
    buyer_product_status: true,
    seller_product_status: true,
    unlimited_stock: true,
    stock: 9999,
    multi: true,
    start_cut_off: "23:55",
    end_cut_off: "00:05",
    desc: "Pulsa Reguler Indosat 50.000"
  },

  // --- PLN: TOKEN LISTRIK ---
  {
    buyer_sku_code: "PLN20",
    product_name: "PLN 20.000",
    category: "PLN",
    brand: "PLN",
    type: "Umum",
    seller_name: "PLN Persero",
    price: 20100,
    buyer_product_status: true,
    seller_product_status: true,
    unlimited_stock: true,
    stock: 9999,
    multi: true,
    start_cut_off: "23:55",
    end_cut_off: "00:05",
    desc: "Token Listrik Prabayar PLN 20.000"
  },
  {
    buyer_sku_code: "PLN50",
    product_name: "PLN 50.000",
    category: "PLN",
    brand: "PLN",
    type: "Umum",
    seller_name: "PLN Persero",
    price: 50100,
    buyer_product_status: true,
    seller_product_status: true,
    unlimited_stock: true,
    stock: 9999,
    multi: true,
    start_cut_off: "23:55",
    end_cut_off: "00:05",
    desc: "Token Listrik Prabayar PLN 50.000"
  },
  {
    buyer_sku_code: "PLN100",
    product_name: "PLN 100.000",
    category: "PLN",
    brand: "PLN",
    type: "Umum",
    seller_name: "PLN Persero",
    price: 100100,
    buyer_product_status: true,
    seller_product_status: true,
    unlimited_stock: true,
    stock: 9999,
    multi: true,
    start_cut_off: "23:55",
    end_cut_off: "00:05",
    desc: "Token Listrik Prabayar PLN 100.000"
  },
  {
    buyer_sku_code: "PLN200",
    product_name: "PLN 200.000",
    category: "PLN",
    brand: "PLN",
    type: "Umum",
    seller_name: "PLN Persero",
    price: 200100,
    buyer_product_status: true,
    seller_product_status: true,
    unlimited_stock: true,
    stock: 9999,
    multi: true,
    start_cut_off: "23:55",
    end_cut_off: "00:05",
    desc: "Token Listrik Prabayar PLN 200.000"
  }
];

export const DEFAULT_PASCA_PRODUCTS: DigiflazzProduct[] = [
  {
    buyer_sku_code: "PLNPOSTPAID",
    product_name: "PLN Pascabayar",
    category: "Pascabayar",
    brand: "PLN PASCA",
    type: "Tagihan",
    seller_name: "PLN Persero",
    price: 0,
    buyer_product_status: true,
    seller_product_status: true,
    unlimited_stock: true,
    stock: 9999,
    multi: true,
    start_cut_off: "23:55",
    end_cut_off: "00:05",
    desc: "Pembayaran Tagihan Listrik PLN Pascabayar Bulanan"
  },
  {
    buyer_sku_code: "BPJSKS",
    product_name: "BPJS Kesehatan",
    category: "Pascabayar",
    brand: "BPJS",
    type: "Tagihan",
    seller_name: "BPJS Kesehatan",
    price: 0,
    buyer_product_status: true,
    seller_product_status: true,
    unlimited_stock: true,
    stock: 9999,
    multi: true,
    start_cut_off: "23:55",
    end_cut_off: "00:05",
    desc: "Pembayaran Iuran BPJS Kesehatan"
  },
  {
    buyer_sku_code: "PDAMKOTA",
    product_name: "PDAM Air Minum",
    category: "Pascabayar",
    brand: "PDAM",
    type: "Tagihan",
    seller_name: "PDAM Tirta",
    price: 0,
    buyer_product_status: true,
    seller_product_status: true,
    unlimited_stock: true,
    stock: 9999,
    multi: true,
    start_cut_off: "23:55",
    end_cut_off: "00:05",
    desc: "Pembayaran Tagihan Air PDAM"
  },
  {
    buyer_sku_code: "TELKOMINDIHOME",
    product_name: "Telkom IndiHome / Speedy",
    category: "Pascabayar",
    brand: "TELKOM",
    type: "Tagihan",
    seller_name: "Telkom Indonesia",
    price: 0,
    buyer_product_status: true,
    seller_product_status: true,
    unlimited_stock: true,
    stock: 9999,
    multi: true,
    start_cut_off: "23:55",
    end_cut_off: "00:05",
    desc: "Pembayaran Tagihan Internet Telkom IndiHome"
  }
];
