import re

with open('/app/applet/server.ts', 'r', encoding='utf-8') as f:
    text = f.read()

# 1. Webhook - Sukses
webhook_sukses_old = r'''msg = `HOREE! Sukses, sayang! 🎉🎊 Pesananmu sudah diproses otomatis! 💖🌈\n\n📄 Nota Sukses:\n\n\n*E4 STORE*\nJl. Zamrud Depan Zamrud 2 RT 42\nWA: 6285169959218\n------------------------------------\n*Order ID:*\n${ref_id}\n*Tanggal:*\n${dateStr}\n*ID Pelanggan:*\n${tx.target}\n*Nama:*\n${member ? (member.name || "-") : "-"}\n------------------------------------\n*Token / SN:*\n${sn}\n------------------------------------\n*Pembelian:*\n${tx.product}\n------------------------------------\n*Total:* Rp ${tx.price.toLocaleString('id-ID')}\n------------------------------------\n*Status:* ✅ SUKSES (LUNAS)\n------------------------------------\nTerimakasih telah berbelanja di E4 Store!\n🐾 Chuna ~ Asisten Imutmu siap bantu 24 jam!`;'''
webhook_sukses_new = r'''msg = `🎉 HOREE! Sukses, Kak! Pesanan sudah diproses otomatis oleh E4 Store.\n${tx.product} udah masuk ke akun ${nama}, siap buat digunakan! 💪🔥\n\n📄 Nota Sukses:\n\n*E4 STORE*\nJl. Zamrud Depan Zamrud 2 RT 42\nWA: 6285169959218\n------------------------------------\nOrder ID    : ${ref_id}\nTanggal     : ${dateStr}\nID Pelanggan: ${tx.target}\nNama        : ${nama}\nToken/SN    : ${sn}\nPembelian   : ${tx.product}\nTotal       : Rp ${tx.price.toLocaleString('id-ID')}\nStatus      : ✅ SUKSES (LUNAS)\n------------------------------------\nTerimakasih telah berbelanja di E4 Store!\n🐾 Chuna ~ Asisten Imutmu siap bantu 24 jam!\n\nKalau mau tanya-tanya atau order lagi, langsung chat Chuna di Bot Telegram, ya!\n👉 https://t.me/Chuna_Chan_bot\n\nChuna tunggu chat dari Kakak! 😊💖`;'''

text = text.replace(webhook_sukses_old, webhook_sukses_new)

# 1. Webhook - Gagal
webhook_gagal_old = r'''msg = `❌ TRANSAKSI GAGAL\n\n📦 Produk: ${tx.product}\n🎯 Tujuan: ${tx.target}\n\nStatus: Gagal ❌\nKeterangan: ${data.message || 'Dibatalkan'}\n${refundMsg}\n\nYah, gagal nih, sayang! Tapi Chuna yakin kamu pasti bisa coba lagi. Hubungi Bos chuna di WA 6285169959218 ya! 💪😘`;'''
webhook_gagal_new = r'''msg = `❌ Maaf Kak, pembayaran untuk pesanan Kakak gagal diproses.\nMungkin ada kesalahan data atau saldo kurang. Coba cek lagi ya, atau hubungi Chuna untuk bantuan.\n\nKeterangan: ${data.message || 'Dibatalkan'}\n\n📦 Produk: ${tx.product}\n🎯 Tujuan: ${tx.target} (${nama})\n\n${refundMsg}\n\nJangan khawatir, Kakak bisa coba ulang kapan saja.\nKalau butuh bantuan, chat Chuna di Bot Telegram:\n👉 https://t.me/Chuna_Chan_bot\n\nChuna siap bantu dengan senyum! 😊💪`;'''

text = text.replace(webhook_gagal_old, webhook_gagal_new)

# 2. Prepaid - Pending
prepaid_pending_old = r'''msg = `⏳ TRANSAKSI SEDANG DIPROSES PUSAT\n📦 Produk: ${product.product_name}\n🎯 Tujuan: ${targetNo}\nStatus: Pending ⏳\nPesanan kakak sedang diproses oleh sistem pusat.\nChuna dari E4 Store minta sabar ya, sayang!\nSebentar lagi selesai kok, jangan kemana-mana dulu~\nSambil nunggu, Chuna siapin cemilan buat kamu! 🚗💨`;'''
prepaid_pending_new = r'''msg = `⏳ Hai Kak, pesanan Kakak sedang diproses oleh sistem pusat E4 Store.\nMohon tunggu beberapa saat, nanti akan kami kabari jika sudah selesai.\n\n📦 Produk: ${product.product_name}\n🎯 Tujuan: ${targetNo} (${member.name || "-"})\n\nKalau mau cek status atau tanya-tanya, langsung chat Chuna di Bot Telegram aja ya!\n👉 https://t.me/Chuna_Chan_bot\n\nChuna tunggu kabar baik dari Kakak! 😊`;'''

text = text.replace(prepaid_pending_old, prepaid_pending_new)

# 2. Prepaid - Sukses
prepaid_sukses_old = r'''msg = `HOREE! Sukses, sayang! 🎉🎊 Chuna sampai joget-joget di depan kasir! Pesananmu sudah masuk, semua serba menyenangkan! Makasih ya udah percaya sama E4 Store dan Chuna yang imut ini. Kalau ada kendala, Chuna siap sedia 24 jam di WA. Semoga hari-harimu makin cerah! 💖🌈\n\n📄 Nota Sukses Prabayar:\n\n*E4 STORE*\nJl. Zamrud Depan Zamrud 2 RT 42\nWA: 6285169959218\n------------------------------------\n*Order ID:*\n${pay_ref_id}\n*Tanggal:*\n${dateStr}\n*ID Pelanggan:*\n${targetNo}\n*Nama:*\n${member.name || "-"}\n------------------------------------\n*Token / SN:*\n${sn}\n------------------------------------\n*Pembelian:*\n${product.product_name}\n------------------------------------\n*Total:* Rp ${total.toLocaleString('id-ID')}\n------------------------------------\n*Status:* ✅ SUKSES (LUNAS)\n------------------------------------\n*Pembayaran:*\n${paymentInfo}\n------------------------------------\n_Melalui WhatsApp ini, Anda akan menerima informasi\n berupa notifikasi terkait transaksi Anda di *E4 Store*_\n------------------------------------\nTerimakasih telah berbelanja di E4 Store!\n🐾 Chuna ~ Asisten Imutmu siap bantu 24 jam!\n📱 WA: 6285169959218\n------------------------------------`;'''
prepaid_sukses_new = r'''msg = `🎉 HOREE! Sukses, Kak! Pesanan sudah diproses otomatis oleh E4 Store.\n${product.product_name} udah masuk ke akun ${member.name || "-"}, siap buat digunakan! 💪🔥\n\n📄 Nota Sukses Prabayar:\n\n*E4 STORE*\nJl. Zamrud Depan Zamrud 2 RT 42\nWA: 6285169959218\n------------------------------------\nOrder ID    : ${pay_ref_id}\nTanggal     : ${dateStr}\nID Pelanggan: ${targetNo}\nNama        : ${member.name || "-"}\nToken/SN    : ${sn}\nPembelian   : ${product.product_name}\nTotal       : Rp ${total.toLocaleString('id-ID')}\nStatus      : ✅ SUKSES (LUNAS)\n------------------------------------\n*Pembayaran:*\n${paymentInfo}\n------------------------------------\nTerimakasih telah berbelanja di E4 Store!\n🐾 Chuna ~ Asisten Imutmu siap bantu 24 jam!\n\nKalau mau tanya-tanya atau order lagi, langsung chat Chuna di Bot Telegram, ya!\n👉 https://t.me/Chuna_Chan_bot\n\nChuna tunggu chat dari Kakak! 😊💖`;'''

text = text.replace(prepaid_sukses_old, prepaid_sukses_new)

# 2. Prepaid - Gagal
prepaid_gagal_old = r'''msg = `❌ TRANSAKSI GAGAL\n📦 Produk: ${product.product_name}\n🎯 Tujuan: ${targetNo}\nStatus: Gagal ❌\nKeterangan: ${payJson.data.message || 'Dibatalkan'}\n${method === 'saldo' ? '✅ Saldo sebesar Rp ' + total.toLocaleString('id-ID') + ' telah dikembalikan ke akunmu!' : (method === 'utang' ? '✅ Utang sebesar Rp ' + total.toLocaleString('id-ID') + ' telah dibatalkan!' : '✅ Silakan kembalikan uang Cash sebesar Rp ' + total.toLocaleString('id-ID') + ' kepada pelanggan.')}\n\nYah, gagal nih, sayang! Tapi Chuna yakin kamu pasti\nbisa coba lagi. Cek data pembayaranmu ya, atau\nhubungi Bos chuna  di WA 6285169959218 buat link whatsapp, nanti Chuna\nbantuin dengan senyum manis! Semangat, jangan\nnangis dulu~ Chuna di sini buat kamu! 💪😘`;'''
prepaid_gagal_new = r'''let refundMsg = method === 'saldo' ? '✅ Saldo sebesar Rp ' + total.toLocaleString('id-ID') + ' telah dikembalikan ke akunmu!' : (method === 'utang' ? '✅ Utang sebesar Rp ' + total.toLocaleString('id-ID') + ' telah dibatalkan!' : '✅ Silakan kembalikan uang Cash sebesar Rp ' + total.toLocaleString('id-ID') + ' kepada pelanggan.');
                    msg = `❌ Maaf Kak, pembayaran untuk pesanan Kakak gagal diproses.\nMungkin ada kesalahan data atau saldo kurang. Coba cek lagi ya, atau hubungi Chuna untuk bantuan.\n\nKeterangan: ${payJson.data.message || 'Dibatalkan'}\n\n📦 Produk: ${product.product_name}\n🎯 Tujuan: ${targetNo} (${member.name || "-"})\n\n${refundMsg}\n\nJangan khawatir, Kakak bisa coba ulang kapan saja.\nKalau butuh bantuan, chat Chuna di Bot Telegram:\n👉 https://t.me/Chuna_Chan_bot\n\nChuna siap bantu dengan senyum! 😊💪`;'''

text = text.replace(prepaid_gagal_old, prepaid_gagal_new)

# 3. Pasca - Pending
pasca_pending_old = r'''msg = `⏳ TRANSAKSI SEDANG DIPROSES PUSAT\n📦 Tagihan: ${stateData.product.product_name}\n🎯 Tujuan: ${customerNo}\nStatus: Pending ⏳\n\nPesanan kakak sedang diproses oleh sistem pusat.\nChuna dari E4 Store minta sabar ya, sayang!\nSebentar lagi selesai kok, jangan kemana-mana dulu~\nSambil nunggu, Chuna siapin cemilan buat kamu! 🚗💨`;'''
pasca_pending_new = r'''msg = `⏳ Hai Kak, pesanan Kakak sedang diproses oleh sistem pusat E4 Store.\nMohon tunggu beberapa saat, nanti akan kami kabari jika sudah selesai.\n\n📦 Tagihan: ${stateData.product.product_name}\n🎯 Tujuan: ${customerNo} (${checkResult.customer_name || "-"})\n\nKalau mau cek status atau tanya-tanya, langsung chat Chuna di Bot Telegram aja ya!\n👉 https://t.me/Chuna_Chan_bot\n\nChuna tunggu kabar baik dari Kakak! 😊`;'''

text = text.replace(pasca_pending_old, pasca_pending_new)

# 3. Pasca - Sukses
pasca_sukses_old = r'''msg = `HOREE! Pembayaran Sukses, sayang! 🎉🎊\n\n📄 Nota Sukses Pascabayar:\n\n*E4 STORE*\nJl. Zamrud Depan Zamrud 2 RT 42\nWA: 6285169959218\n------------------------------------\n*Order ID:*\n${pay_ref_id}\n*Tanggal:*\n${dateStr}\n*ID Pelanggan:*\n${customerNo}\n*Nama:*\n${checkResult.customer_name || "-"}\n------------------------------------\n*Token / SN:*\n${sn}\n------------------------------------\n*Pembayaran:*\n${stateData.product.product_name}\n------------------------------------\n*Total:* Rp ${total.toLocaleString('id-ID')}\n------------------------------------\n*Status:* ✅ SUKSES (LUNAS)\n------------------------------------\n*Pembayaran:*\n${paymentInfo}\n------------------------------------\n_Melalui WhatsApp ini, Anda akan menerima informasi\n berupa notifikasi terkait transaksi Anda di *E4 Store*_\n------------------------------------\nTerimakasih telah berbelanja di E4 Store!\n🐾 Chuna ~ Asisten Imutmu siap bantu 24 jam!\n📱 WA: 6285169959218\n------------------------------------`;'''
pasca_sukses_new = r'''msg = `🎉 HOREE! Pembayaran Sukses, Kak! Pesanan sudah diproses otomatis oleh E4 Store.\nTagihan ${stateData.product.product_name} untuk ${checkResult.customer_name || "-"} udah berhasil dibayar! 💪🔥\n\n📄 Nota Sukses Pascabayar:\n\n*E4 STORE*\nJl. Zamrud Depan Zamrud 2 RT 42\nWA: 6285169959218\n------------------------------------\nOrder ID    : ${pay_ref_id}\nTanggal     : ${dateStr}\nID Pelanggan: ${customerNo}\nNama        : ${checkResult.customer_name || "-"}\nToken/SN    : ${sn}\nPembayaran  : ${stateData.product.product_name}\nTotal       : Rp ${total.toLocaleString('id-ID')}\nStatus      : ✅ SUKSES (LUNAS)\n------------------------------------\n*Pembayaran:*\n${paymentInfo}\n------------------------------------\nTerimakasih telah berbelanja di E4 Store!\n🐾 Chuna ~ Asisten Imutmu siap bantu 24 jam!\n\nKalau mau tanya-tanya atau order lagi, langsung chat Chuna di Bot Telegram, ya!\n👉 https://t.me/Chuna_Chan_bot\n\nChuna tunggu chat dari Kakak! 😊💖`;'''

text = text.replace(pasca_sukses_old, pasca_sukses_new)

# 3. Pasca - Gagal
pasca_gagal_old = r'''msg = `❌ TRANSAKSI GAGAL\n📦 Produk: ${stateData.product.product_name}\n🎯 Tujuan: ${customerNo}\nStatus: Gagal ❌\nKeterangan: ${payJson.data.message || 'Dibatalkan'}\n${method === 'saldo' ? '✅ Saldo sebesar Rp ' + total.toLocaleString('id-ID') + ' telah dikembalikan ke akunmu!' : (method === 'utang' ? '✅ Utang sebesar Rp ' + total.toLocaleString('id-ID') + ' telah dibatalkan!' : '✅ Silakan kembalikan uang Cash sebesar Rp ' + total.toLocaleString('id-ID') + ' kepada pelanggan.')}\n\nYah, gagal nih, sayang! Tapi Chuna yakin kamu pasti\nbisa coba lagi. Cek data pembayaranmu ya, atau\nhubungi Bos chuna  di WA 6285169959218 buat link whatsapp, nanti Chuna\nbantuin dengan senyum manis! Semangat, jangan\nnangis dulu~ Chuna di sini buat kamu! 💪😘`;'''
pasca_gagal_new = r'''let refundMsg = method === 'saldo' ? '✅ Saldo sebesar Rp ' + total.toLocaleString('id-ID') + ' telah dikembalikan ke akunmu!' : (method === 'utang' ? '✅ Utang sebesar Rp ' + total.toLocaleString('id-ID') + ' telah dibatalkan!' : '✅ Silakan kembalikan uang Cash sebesar Rp ' + total.toLocaleString('id-ID') + ' kepada pelanggan.');
                    msg = `❌ Maaf Kak, pembayaran untuk pesanan Kakak gagal diproses.\nMungkin ada kesalahan data atau saldo kurang. Coba cek lagi ya, atau hubungi Chuna untuk bantuan.\n\nKeterangan: ${payJson.data.message || 'Dibatalkan'}\n\n📦 Tagihan: ${stateData.product.product_name}\n🎯 Tujuan: ${customerNo} (${checkResult.customer_name || "-"})\n\n${refundMsg}\n\nJangan khawatir, Kakak bisa coba ulang kapan saja.\nKalau butuh bantuan, chat Chuna di Bot Telegram:\n👉 https://t.me/Chuna_Chan_bot\n\nChuna siap bantu dengan senyum! 😊💪`;'''

text = text.replace(pasca_gagal_old, pasca_gagal_new)

with open('/app/applet/server.ts', 'w', encoding='utf-8') as f:
    f.write(text)

print("Replacement complete.")
