import re

with open('/app/applet/server.ts', 'r', encoding='utf-8') as f:
    content = f.read()

# Pattern 1 (Line 224): Auto process success
content = re.sub(
    r'msg = `HOREE! Sukses, sayang! 🎉🎊 Pesananmu sudah diproses otomatis! 💖🌈\\n\\n📄 Nota Sukses:\\n\\n\`\`\`\\n\*E4 STORE\*\\nJl\. Zamrud Depan Zamrud 2 RT 42\\nWA: 6285169959218\\n------------------------------------\\nOrder ID      : \$\{ref_id\}\\nTanggal       : \$\{dateStr\}\\nID Pelanggan  : \$\{tx\.target\}\\nNama          : \$\{member \? \(member\.name \|\| "-"\) : "-"\}\\n------------------------------------\\nToken \/ SN    : \$\{sn\}\\n------------------------------------\\nPembelian     : \$\{tx\.product\}\\n------------------------------------\\nTotal         : Rp \$\{tx\.price\.toLocaleString\(\'id-ID\'\)\}\\n------------------------------------\\nStatus        : ✅ SUKSES \(LUNAS\)\\n------------------------------------\\nTerimakasih telah berbelanja di E4 Store!\\n🐾 Chuna ~ Asisten Imutmu siap bantu 24 jam!\\n\`\`\``;',
    r'''msg = `HOREE! Sukses, sayang! 🎉🎊 Pesananmu sudah diproses otomatis! 💖🌈\n\n📄 Nota Sukses:\n\n*E4 STORE*\nJl. Zamrud Depan Zamrud 2 RT 42\nWA: 6285169959218\n------------------------------------\n*Order ID:*\n${ref_id}\n\n*Tanggal:*\n${dateStr}\n\n*ID Pelanggan:*\n${tx.target}\n\n*Nama:*\n${member ? (member.name || "-") : "-"}\n------------------------------------\n*Token / SN:*\n${sn}\n------------------------------------\n*Pembelian:*\n${tx.product}\n------------------------------------\n*Total:* Rp ${tx.price.toLocaleString('id-ID')}\n------------------------------------\n*Status:* ✅ SUKSES (LUNAS)\n------------------------------------\nTerimakasih telah berbelanja di E4 Store!\n🐾 Chuna ~ Asisten Imutmu siap bantu 24 jam!`;''',
    content
)

# Pattern 2 (Line 1049): Prabayar success
content = re.sub(
    r'msg = `HOREE! Sukses, sayang! 🎉🎊 Chuna sampai joget-joget di depan kasir! Pesananmu sudah masuk, semua serba menyenangkan! Makasih ya udah percaya sama E4 Store dan Chuna yang imut ini. Kalau ada kendala, Chuna siap sedia 24 jam di WA. Semoga hari-harimu makin cerah! 💖🌈\\n\\n📄 Nota Sukses Prabayar:\\n\`\`\`\\n\*E4 STORE\*\\nJl\. Zamrud Depan Zamrud 2 RT 42\\nWA: 6285169959218\\n------------------------------------\\nOrder ID      : \$\{pay_ref_id\}\\nTanggal       : \$\{dateStr\}\\nID Pelanggan  : \$\{targetNo\}\\nNama          : \$\{member\.name \|\| "-"\}\\n------------------------------------\\nToken \/ SN    : \$\{sn\}\\n------------------------------------\\nPembelian     : \$\{product\.product_name\}\\n------------------------------------\\nTotal         : Rp \$\{total\.toLocaleString\(\'id-ID\'\)\}\\n------------------------------------\\nStatus        : ✅ SUKSES \(LUNAS\)\\n------------------------------------\\nPembayaran    :\\n\$\{paymentInfo\}\\n------------------------------------\\n_Melalui WhatsApp ini, Anda akan menerima informasi\\n berupa notifikasi terkait transaksi Anda di \*E4 Store\*_\\n------------------------------------\\nTerimakasih telah berbelanja di E4 Store!\\n🐾 Chuna ~ Asisten Imutmu siap bantu 24 jam!\\n📱 WA: 6285169959218\\n------------------------------------\\n\`\`\``;',
    r'''msg = `HOREE! Sukses, sayang! 🎉🎊 Chuna sampai joget-joget di depan kasir! Pesananmu sudah masuk, semua serba menyenangkan! Makasih ya udah percaya sama E4 Store dan Chuna yang imut ini. Kalau ada kendala, Chuna siap sedia 24 jam di WA. Semoga hari-harimu makin cerah! 💖🌈\n\n📄 Nota Sukses Prabayar:\n\n*E4 STORE*\nJl. Zamrud Depan Zamrud 2 RT 42\nWA: 6285169959218\n------------------------------------\n*Order ID:*\n${pay_ref_id}\n\n*Tanggal:*\n${dateStr}\n\n*ID Pelanggan:*\n${targetNo}\n\n*Nama:*\n${member.name || "-"}\n------------------------------------\n*Token / SN:*\n${sn}\n------------------------------------\n*Pembelian:*\n${product.product_name}\n------------------------------------\n*Total:* Rp ${total.toLocaleString('id-ID')}\n------------------------------------\n*Status:* ✅ SUKSES (LUNAS)\n------------------------------------\n*Pembayaran:*\n${paymentInfo}\n------------------------------------\n_Melalui WhatsApp ini, Anda akan menerima informasi berupa notifikasi terkait transaksi Anda di *E4 Store*_\n------------------------------------\nTerimakasih telah berbelanja di E4 Store!\n🐾 Chuna ~ Asisten Imutmu siap bantu 24 jam!\n📱 WA: 6285169959218\n------------------------------------`;''',
    content
)

# Pattern 3 (Line 1221): Pascabayar success
content = re.sub(
    r'msg = `HOREE! Pembayaran Sukses, sayang! 🎉🎊\\n\\n📄 Nota Sukses Pascabayar:\\n\`\`\`\\n\*E4 STORE\*\\nJl\. Zamrud Depan Zamrud 2 RT 42\\nWA: 6285169959218\\n------------------------------------\\nOrder ID      : \$\{pay_ref_id\}\\nTanggal       : \$\{dateStr\}\\nID Pelanggan  : \$\{customerNo\}\\nNama          : \$\{checkResult\.customer_name \|\| "-"\}\\n------------------------------------\\nToken \/ SN    : \$\{sn\}\\n------------------------------------\\nPembayaran    : \$\{stateData\.product\.product_name\}\\n------------------------------------\\nTotal         : Rp \$\{total\.toLocaleString\(\'id-ID\'\)\}\\n------------------------------------\\nStatus        : ✅ SUKSES \(LUNAS\)\\n------------------------------------\\nPembayaran    :\\n\$\{paymentInfo\}\\n------------------------------------\\n_Melalui WhatsApp ini, Anda akan menerima informasi\\n berupa notifikasi terkait transaksi Anda di \*E4 Store\*_\\n------------------------------------\\nTerimakasih telah berbelanja di E4 Store!\\n🐾 Chuna ~ Asisten Imutmu siap bantu 24 jam!\\n📱 WA: 6285169959218\\n------------------------------------\\n\`\`\``;',
    r'''msg = `HOREE! Pembayaran Sukses, sayang! 🎉🎊\n\n📄 Nota Sukses Pascabayar:\n\n*E4 STORE*\nJl. Zamrud Depan Zamrud 2 RT 42\nWA: 6285169959218\n------------------------------------\n*Order ID:*\n${pay_ref_id}\n\n*Tanggal:*\n${dateStr}\n\n*ID Pelanggan:*\n${customerNo}\n\n*Nama:*\n${checkResult.customer_name || "-"}\n------------------------------------\n*Token / SN:*\n${sn}\n------------------------------------\n*Pembayaran:*\n${stateData.product.product_name}\n------------------------------------\n*Total:* Rp ${total.toLocaleString('id-ID')}\n------------------------------------\n*Status:* ✅ SUKSES (LUNAS)\n------------------------------------\n*Pembayaran:*\n${paymentInfo}\n------------------------------------\n_Melalui WhatsApp ini, Anda akan menerima informasi berupa notifikasi terkait transaksi Anda di *E4 Store*_\n------------------------------------\nTerimakasih telah berbelanja di E4 Store!\n🐾 Chuna ~ Asisten Imutmu siap bantu 24 jam!\n📱 WA: 6285169959218\n------------------------------------`;''',
    content
)

with open('/app/applet/server.ts', 'w', encoding='utf-8') as f:
    f.write(content)

